### ISSUE TITLE
vs Sveltekit

### ISSUE THREAD

**Issue by sensiblearts** [filipecabaco/ex_tauri#2]
Greetings:

I read your [blogpost](https://crabnebula.dev/blog/tauri-elixir-phoenix/), which links to ex_tauri here, and am wondering if you can advise me: 

I'm starting a new project and trying to decide whether to pursue a Phoenix LiveView + Tauri solution (or go with a safer choice, SvelteKit + Tauri).

I would prefer to use LiveView, but I hope to ship a desktop app by October 2024.

Do you think the [tradeoffs described in your blog post](https://crabnebula.dev/blog/tauri-elixir-phoenix/) can be resolved by then? (I don't know Rust, but have done C++, and could learn and try to help you.)

Thanks you,
David Alm

**Comment by filipecabaco** [comment]
👋 

Tricky to say, I will start to migrate to tauri v2 beta during this week and I would say ex_tauri will become stable when tauri v2 becomes stable 😣

The tradeoffs can be fixed "easily" depending on the migration mentioned above 👍 

I might be able to give a more concrete response later this week

**Comment by sensiblearts** [comment]
Thank you **so much** for your prompt reply.

But yesterday I had an insight and decided to "suck it up" and relearn JavaScript (Svelte).  The web app will be mostly a LiveView app with an embedded Svelte SPA, and the desktop part will be Tauri-Svelte (mirroring the SPA).

A number of tech and business advantages outweigh my desire to use LiveView. (E.g., there's a chance that I might want to add mobile apps down the road, and Elixir won't work there as I understand it, because the main app would have to spawn a separate erlang OS process.) 

So thank you again. Looking forward to learning Tauri and Rust.
